name: DevSecOps Pipeline

on:
  push:
    paths:
      - 'python-weather-app/**'
      - 'cpp-calculator/**'
      - '.github/workflows/**'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # TruffleHog needs the full history to find leaked secrets in old commits

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

  python-security-scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python-weather-app
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.2'

    - name: Install Security Tools
      run: pip install bandit pip-audit

    - name: Run Bandit (SAST)
      # Excluding tests and ignoring low-severity "assert" warnings
      run: bandit -r . -x ./test_app.py -ll

    - name: Run pip-audit (SCA)
      # This scans your requirements.txt for known vulnerabilities
      run: pip-audit -r requirements.txt

  test:
    needs: python-security-scan # The tests only run if the security scan passes!
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run Pytest
      run: |
        pip install pytest
        pytest test_app.py
  
  cpp-build-and-scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cpp-calculator
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install cppcheck

      - name: Run Cppcheck (SAST for C++)
        # This checks for memory leaks and buffer overflows
        run: cppcheck --enable=all --error-exitcode=1 .

      - name: Build C++ App
        run: |
          g++ -o calculator main.cpp
          ./calculator

  